name: Discord PR Notify

on:
  pull_request:
    branches: ["main"]

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

- name: Discord Notify
  run: |
    curl -H "Content-Type: application/json" \
    -d '{"content":"🚀 Novo evento no repositório"}' \
    ${{ secrets.DISCORD_WEBHOOK }}